# Generated by Django 3.1.5 on 2021-03-02 05:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_name', models.CharField(max_length=50, verbose_name='ブランド名')),
                ('date_purchase', models.DateField(blank=True, null=True, verbose_name='購入日')),
                ('season', models.CharField(choices=[('春', '春'), ('夏', '夏'), ('秋', '秋'), ('冬', '冬')], max_length=5, verbose_name='季節')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='写真')),
                ('price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='価格')),
                ('favorite', models.BooleanField(blank=True, default=False, null=True, verbose_name='お気に入り')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.parts', verbose_name='部位')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
