# Generated by Django 3.1.5 on 2021-01-29 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'HEIC'])]),
        ),
    ]
