# Generated by Django 3.1.5 on 2021-03-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_post_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cloth_name',
            field=models.CharField(max_length=50, verbose_name='Brand Name'),
        ),
    ]
