# Generated by Django 3.1.5 on 2021-03-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_auto_20210306_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_purchase',
            field=models.DateField(blank=True, null=True, verbose_name='購入日全'),
        ),
    ]
