# Generated by Django 3.1.5 on 2021-03-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_auto_20210306_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cloth_name',
            field=models.CharField(max_length=50, verbose_name='ブランド'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_purchase',
            field=models.DateField(blank=True, null=True, verbose_name='購入日'),
        ),
    ]
